export const IMAGES = {
  "animals": {
    "Ant": "Property 1=Ant.png",
    "Bear": "Property 1=Bear.png",
    "Bison": "Property 1=Bison.png",
    "Buffalo": "Property 1=Buffalo.png",
    "Cat 1": "Property 1=Cat 1.png",
    "Cat 2": "Property 1=Cat 2.png",
    // "Cat 3": "Property 1=Cat 3.png",
    // "Cat 4": "Property 1=Cat 4.png",
    // "Cat 5": "Property 1=Cat 5.png",
    "Chicken": "Property 1=Chicken.png",
    "Chococat": "Property 1=Chococat.png",
    "Cow": "Property 1=Cow.png",
    "Crocodile": "Property 1=Crocodile.png",
    "Dog 1": "Property 1=Dog 1.png",
    "Dog 2": "Property 1=Dog 2.png",
    // "Dog 3": "Property 1=Dog 3.png",
    // "Dog 4": "Property 1=Dog 4.png",
    // "Dog 5": "Property 1=Dog 5.png",
    "Doraemon": "Property 1=Doraemon.png",
    "Duck": "Property 1=Duck.png",
    "Eagle": "Property 1=Eagle.png",
    "Elephant": "Property 1=Elephant.png",
    "Fox": "Property 1=Fox.png",
    "Giraffe": "Property 1=Giraffe.png",
    "Gorilla": "Property 1=Gorilla.png",
    "Hedgehog": "Property 1=Hedgehog.png",
    "Hello Kitty": "Property 1=Hello Kitty.png",
    "Hippo": "Property 1=Hippo.png",
    "Horse": "Property 1=Horse.png",
    "Keroppi": "Property 1=Keroppi.png",
    "Koala": "Property 1=Koala.png",
    "Leopard": "Property 1=Leopard.png",
    "Lion": "Property 1=Lion.png",
    "Monkey": "Property 1=Monkey.png",
    "Moose": "Property 1=Moose.png",
    "Mouse": "Property 1=Mouse.png",
    "Otter": "Property 1=Otter.png",
    "Owl": "Property 1=Owl.png",
    "Panda": "Property 1=Panda.png",
    "Penguin": "Property 1=Penguin.png",
    "Pig": "Property 1=Pig.png",
    "Pikachu": "Property 1=Pikachu.png",
    "Raccoon": "Property 1=Raccoon.png",
    "Sheep": "Property 1=Sheep.png",
    "Sloth": "Property 1=Sloth.png",
    "Snake": "Property 1=Snake.png",
    "Squirrel": "Property 1=Squirrel.png",
    "Tiger": "Property 1=Tiger.png",
    "Wolf": "Property 1=Wolf.png",
    "Zebra": "Property 1=Zebra.png"
  },
  "fruits": {
    "Avocado": "Property 1=Avocado.png",
    "Coconut cut": "Property 1=Coconut cut.png",
    "Lemon": "Property 1=Lemon.png",
    "Orange": "Property 1=Orange.png",
    "Peach": "Property 1=Peach.png",
    "Pear": "Property 1=Pear.png",
    "Pomegranate": "Property 1=Pomegranate.png",
    "Red Apple": "Property 1=Red Apple.png"
  },
  "furniture": {
    "Armchair": "Property 1=Armchair.png",
    "Bed": "Property 1=Bed.png",
    "Bedside table": "Property 1=Bedside table.png",
    "Bookcase": "Property 1=Bookcase.png",
    "Closet": "Property 1=Closet.png",
    "Desk": "Property 1=Desk.png",
    "Dresser": "Property 1=Dresser.png",
    "Floor lamp": "Property 1=Floor lamp.png",
    "Floor mirror": "Property 1=Floor mirror.png",
    "Mirror": "Property 1=Mirror.png",
    "Pouf": "Property 1=Pouf.png",
    "Round chair": "Property 1=Round chair.png",
    "Sofa": "Property 1=Sofa.png",
    "Stool": "Property 1=Stool.png",
    "Table": "Property 1=Table.png",
    "Wardrobe": "Property 1=Wardrobe.png"
  },
  "vegetables": {
   "Carrot": "Property 1=Carrot.png",
   "Eggplant": "Property 1=Eggplant.png",
   "Pepper": "Property 1=Pepper.png",
   "Potato": "Property 1=Potato.png",
   "Red onion": "Property 1=Red onion.png",
   "Tomato": "Property 1=Tomato.png",
   "Сorn": "Property 1=Сorn.png",
   "Сucumber": "Property 1=Сucumber.png"
  },
  "weather": {
    "clear-day": "Property 1=clear-day.png",
    "clear-night": "Property 1=clear-night.png",
    "cloudy": "Property 1=cloudy.png",
    "fog": "Property 1=fog.png",
    "heavy-showers": "Property 1=heavy-showers.png",
    "heavy-sleet": "Property 1=heavy-sleet.png",
    "heavy-snow": "Property 1=heavy-snow.png",
    "overcast": "Property 1=overcast.png",
    "partly-cloudy-day": "Property 1=partly-cloudy-day.png",
    "partly-cloudy-night": "Property 1=partly-cloudy-night.png",
    "showers": "Property 1=showers.png",
    "sleet": "Property 1=sleet.png",
    "snow": "Property 1=snow.png",
    "thunderstorm-showers": "Property 1=thunderstorm-showers.png",
    "thunderstorm-snow": "Property 1=thunderstorm-snow.png",
    "windy": "Property 1=windy.png"
  }
}
