export const nlNL = {
  "animals": {
    "Ant": "Mier",
    "Bear": "Beer",
    "Bison": "Bizon",
    "Buffalo": "Buffel",
    "Cat 1": "Kat",
    "Cat 2": "Kat",
    "Cat 3": "Kat",
    "Cat 4": "Kat",
    "Cat 5": "Kat",
    "Chicken": "Kip",
    "Chococat": "Chocokat",
    "Cow": "Koe",
    "Crocodile": "Krokodil",
    "Dog 1": "Hond",
    "Dog 2": "Hond",
    "Dog 3": "Hond",
    "Dog 4": "Hond",
    "Dog 5": "Hond",
    "Doraemon": "Doraemon",
    "Duck": "Eend",
    "Eagle": "Adelaar",
    "Elephant": "Olifant",
    "Fox": "Vos",
    "Giraffe": "Giraffe",
    "Gorilla": "Gorilla",
    "Hedgehog": "Egel",
    "Hello Kitty": "Hallo Kitty",
    "Hippo": "Nijlpaard",
    "Horse": "Paard",
    "Keroppi": "Kikker",
    "Koala": "Koala",
    "Leopard": "Luipaard",
    "Lion": "Leeuw",
    "Monkey": "Aap",
    "Moose": "Eland",
    "Mouse": "Muis",
    "Otter": "Otter",
    "Owl": "Uil",
    "Panda": "Panda",
    "Penguin": "pinguïn",
    "Pig": "Varken",
    "Pikachu": "Pikachu",
    "Raccoon": "Wasbeer",
    "Sheep": "Schaap",
    "Sloth": "Luiaard",
    "Snake": "Slang",
    "Squirrel": "Eekhoorn",
    "Tiger": "Tijger",
    "Wolf": "Wolf",
    "Zebra": "Zebra"
  },
  "fruits": {
    "Avocado": "Avocado",
    "Coconut cut": "Kokosnoot",
    "Lemon": "Citroen",
    "Orange": "Oranje",
    "Peach": "Perzik",
    "Pear": "Peer",
    "Pomegranate": "Granaatappel",
    "Red Apple": "Rode appel"
  },
  "furniture": {
    "Armchair": "Fauteuil",
    "Bed": "Bed",
    "Bedside table": "Nachtkastje",
    "Bookcase": "Boekenkast",
    "Closet": "Kast",
    "Desk": "Bureau",
    "Dresser": "Dressoir",
    "Floor lamp": "Vloerlamp",
    "Floor mirror": "Vloer spiegel",
    "Mirror": "Spiegel",
    "Pouf": "Poef",
    "Round chair": "Ronde stoel",
    "Sofa": "Bank",
    "Stool": "Kruk",
    "Table": "Tafel",
    "Wardrobe": "Kledingkast"
  },
  "vegetables": {
    "Carrot": "Wortel",
    "Eggplant": "Aubergine",
    "Pepper": "Peper",
    "Potato": "Aardappel",
    "Red onion": "Rode ui",
    "Tomato": "Tomaat",
    "Corn": "Сorn",
    "Cucumber": "Komkommer"
  },
  "weather": {
    "clear-day": "heldere dag",
    "clear-night": "heldere nacht",
    "cloudy": "bewolkt",
    "fog": "mist",
    "heavy-showers": "hevige douches",
    "heavy-sleet": "zware sneeuwval",
    "heavy-snow": "zware sneeuw",
    "overcast": "bewolkt",
    "partly-cloudy-day": "gedeeltelijk bewolkte dag",
    "partly-cloudy-night": "gedeeltelijk bewolkte nacht",
    "showers": "douches",
    "sleet": "natte sneeuw",
    "snow": "sneeuw",
    "thunderstorm-showers": "onweersbuien",
    "thunderstorm-snow": "onweer-sneeuw",
    "windy": "winderig"
  }
}
